INSERT INTO `sorare-data-341411.analytics.dim_league_structure` VALUES 
    --Champion Europe
    ('ligue-1-fr', 'Champion Europe'),
    ('serie-a-it', 'Champion Europe'),
    ('bundesliga-de', 'Champion Europe'),
    ('premier-league-gb-eng', 'Champion Europe'),
    ('laliga-santander', 'Champion Europe'),
    -- Challenger Europe
    ('primeira-liga-pt', 'Challenger Europe'),
    ('russian-premier-league', 'Challenger Europe'),
    ('eredivisie', 'Challenger Europe'),
    ('jupiler-pro-league', 'Challenger Europe'),
    ('premiership-gb-sct', 'Challenger Europe'),
    ('spor-toto-super-lig', 'Challenger Europe'),
    ('football-league-championship', 'Challenger Europe'),
    ('1-division-dk', 'Challenger Europe'),
    --Champion America
    ('mlspa', 'Champion America'),
    ('liga-mx', 'Champion America'),
    ('superliga-argentina-de-futbol', 'Champion America'),
    ('campeonato-brasileiro-serie-a', 'Champion America'),
    ('primera-division-pe', 'Champion America'),
    ('primera-a', 'Champion America'),
    --Champion Asia
    ('j1-league', 'Champion Asia'),
    ('k-league-1', 'Champion Asia'),
    ('super-league-ch', 'Champion Asia'),
    --All Star
    ('ligue-1-fr', 'All Star'),
    ('serie-a-it', 'All Star'),
    ('bundesliga-de', 'All Star'),
    ('premier-league-gb-eng', 'All Star'),
    ('laliga-santander', 'All Star'),
    ('primeira-liga-pt', 'All Star'),
    ('russian-premier-league', 'All Star'),
    ('eredivisie', 'All Star'),
    ('jupiler-pro-league', 'All Star'),
    ('premiership-gb-sct', 'All Star'),
    ('spor-toto-super-lig', 'All Star'),
    ('football-league-championship', 'All Star'),
    ('1-division-dk', 'All Star'),
    ('mlspa', 'All Star'),
    ('liga-mx', 'All Star'),
    ('superliga-argentina-de-futbol', 'All Star'),
    ('campeonato-brasileiro-serie-a', 'All Star'),
    ('primera-division-pe', 'All Star'),
    ('primera-a', 'All Star'),
    ('j1-league', 'All Star'),
    ('k-league-1', 'All Star'),
    ('super-league-ch', 'All Star')